### ISSUE TITLE
PC版前端不显示视频的问题 @mad_max_ph

### ISSUE THREAD

**Issue by bw2015** [bw2015/ESport3.Issues#6]
接口有输出视频，但是不显示图片的图标
比赛编号：121109

![image](https://user-images.githubusercontent.com/38880080/142716574-bcdb4a8f-bf6c-44ee-aa9f-eefa9da6b612.png)

---

![image](https://user-images.githubusercontent.com/38880080/142716581-b613224e-66b1-4c61-91e9-2457178a3b51.png)

@mad_max_ph

**Comment by easyc0me** [comment]
已处理
